### PR TITLE
BUGFIX: allow suggestion body to be nullable

### PR DESCRIPTION
**Pull request by shdunning**
Fixes Issue #2 (hopefully)

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @shdunning, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @shdunning!

Thank you for signing the Singer Contribution License Agreement.

**Comment by shdunning** [comment]
@nick-mccoy maybe this won't work -- the `catalog.json` doesn't seem to be affected when I run: 

`tap-uservoice -c config.json --discover > catalog.json`

**Comment by nick-mccoy** [comment]
@shdunning, interesting, I ran this locally with the change and it worked for me.  Are you sure you're looking at the right `body` field in the schema?  There are a bunch..

I'm going to merge and deploy this since it's a minimal, non-breaking change and I've tested it locally.

**Comment by shdunning** [comment]
yeah @nick-mccoy -- i forgot to update `tap-uservoice` via `pip install .` 🤦‍♂️

**Pull request merged**
